version: '3'
services:
  app:
    build: .
    image: php:7.2-fpm-stretch
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
  webserver:
    image: nginx:alpine
    ports:
      - "8089:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
  redis:
    image: redis:5
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: workflow
    volumes:
      - database:/var/lib/mysql

volumes:
  database: